INSERT INTO exercises (name, muscle_group, type, created_by) VALUES
  -- Chest
  ('Barbell Bench Press',       'Chest',     'Strength',   NULL),
  ('Incline Barbell Press',     'Chest',     'Strength',   NULL),
  ('Decline Barbell Press',     'Chest',     'Strength',   NULL),
  ('Dumbbell Bench Press',      'Chest',     'Strength',   NULL),
  ('Incline Dumbbell Press',    'Chest',     'Strength',   NULL),
  ('Cable Fly',                 'Chest',     'Strength',   NULL),
  ('Dumbbell Fly',              'Chest',     'Strength',   NULL),
  ('Push-Up',                   'Chest',     'Bodyweight', NULL),
  -- Back
  ('Barbell Deadlift',          'Back',      'Strength',   NULL),
  ('Pull-Up',                   'Back',      'Bodyweight', NULL),
  ('Chin-Up',                   'Back',      'Bodyweight', NULL),
  ('Barbell Row',               'Back',      'Strength',   NULL),
  ('Dumbbell Row',              'Back',      'Strength',   NULL),
  ('Lat Pulldown',              'Back',      'Strength',   NULL),
  ('Seated Cable Row',          'Back',      'Strength',   NULL),
  ('T-Bar Row',                 'Back',      'Strength',   NULL),
  ('Face Pull',                 'Back',      'Strength',   NULL),
  -- Legs
  ('Barbell Squat',             'Legs',      'Strength',   NULL),
  ('Front Squat',               'Legs',      'Strength',   NULL),
  ('Leg Press',                 'Legs',      'Strength',   NULL),
  ('Romanian Deadlift',         'Legs',      'Strength',   NULL),
  ('Leg Curl',                  'Legs',      'Strength',   NULL),
  ('Leg Extension',             'Legs',      'Strength',   NULL),
  ('Hack Squat',                'Legs',      'Strength',   NULL),
  ('Bulgarian Split Squat',     'Legs',      'Strength',   NULL),
  ('Walking Lunge',             'Legs',      'Bodyweight', NULL),
  ('Calf Raise',                'Legs',      'Strength',   NULL),
  -- Shoulders
  ('Overhead Press',            'Shoulders', 'Strength',   NULL),
  ('Dumbbell Shoulder Press',   'Shoulders', 'Strength',   NULL),
  ('Arnold Press',              'Shoulders', 'Strength',   NULL),
  ('Lateral Raise',             'Shoulders', 'Strength',   NULL),
  ('Front Raise',               'Shoulders', 'Strength',   NULL),
  ('Rear Delt Fly',             'Shoulders', 'Strength',   NULL),
  ('Upright Row',               'Shoulders', 'Strength',   NULL),
  -- Arms
  ('Barbell Curl',              'Arms',      'Strength',   NULL),
  ('Dumbbell Curl',             'Arms',      'Strength',   NULL),
  ('Hammer Curl',               'Arms',      'Strength',   NULL),
  ('Preacher Curl',             'Arms',      'Strength',   NULL),
  ('Tricep Pushdown',           'Arms',      'Strength',   NULL),
  ('Skull Crusher',             'Arms',      'Strength',   NULL),
  ('Overhead Tricep Extension', 'Arms',      'Strength',   NULL),
  ('Diamond Push-Up',           'Arms',      'Bodyweight', NULL),
  ('Dip',                       'Arms',      'Bodyweight', NULL),
  -- Core
  ('Plank',                     'Core',      'Bodyweight', NULL),
  ('Crunch',                    'Core',      'Bodyweight', NULL),
  ('Leg Raise',                 'Core',      'Bodyweight', NULL),
  ('Russian Twist',             'Core',      'Bodyweight', NULL),
  ('Ab Wheel Rollout',          'Core',      'Bodyweight', NULL),
  ('Cable Crunch',              'Core',      'Strength',   NULL),
  -- Cardio
  ('Treadmill Run',             'Cardio',    'Cardio',     NULL),
  ('Rowing Machine',            'Cardio',    'Cardio',     NULL),
  ('Stationary Bike',           'Cardio',    'Cardio',     NULL),
  ('Jump Rope',                 'Cardio',    'Cardio',     NULL);
